# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            25b3nk
tagline:          'Tech Blog'
description:      'My Tech and Educational Blog'
url:              https://25b3nk.github.io
baseurl:          /
name:             Bhaskar         

author:
  name:           'Bhaskar'
  url:            https://github.com/25b3nk

twitter_username: csbenk
linkedin_username: bhaskar-chakradhar

paginate:         5

github:
    username:         25b3nk
    url:              https://github.com/25b3nk
    repo:             https://github.com/25b3nk/25b3nk.github.io

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist

google_analytics: UA-172513311-1

#theme: jekyll-theme-hacker
